/*******************************************************************************
* FILE NAME: Options.h                                                         *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Constant declarations for class:                                           *
*     Options                                                                  *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _ICCONST_
#include <icconst.h>
#endif

#ifndef _IVBDEFS_
#include <ivbdefs.h>
#endif

#ifndef WND_Options
#define WND_Options  VBBASEWINDOWID
#endif

#define WNDOFFSET_Options_W_OPTIONS  0
#define WND_Options_W_OPTIONS  WND_Options

#define WND_Options_Canvas  IC_FRAME_CLIENT_ID

#define WNDOFFSET_Options_NB_OPTIONS  1
#define WND_Options_NB_OPTIONS  WND_Options + WNDOFFSET_Options_NB_OPTIONS
#define STRRC_Options_NB_OPTIONS_avlFlyOverShortText  WND_Options_NB_OPTIONS + VBSHORTFLYTEXTOFFSET
#define STRRC_Options_NB_OPTIONS_avlFlyOverLongText  WND_Options_NB_OPTIONS + VBLONGFLYTEXTOFFSET

#define WNDOFFSET_Options_TB_MINES  2
#define WND_Options_TB_MINES  WND_Options + WNDOFFSET_Options_TB_MINES

#define WNDOFFSET_Options_CANVAS_MINE  3
#define WND_Options_CANVAS_MINE  WND_Options + WNDOFFSET_Options_CANVAS_MINE

#define WNDOFFSET_Options_CK_MINES  4
#define WND_Options_CK_MINES  WND_Options + WNDOFFSET_Options_CK_MINES

#define WNDOFFSET_Options_SPIN_NUMBER_OF_MINES  5
#define WND_Options_SPIN_NUMBER_OF_MINES  WND_Options + WNDOFFSET_Options_SPIN_NUMBER_OF_MINES

#define WNDOFFSET_Options_ST_NUMBER_OF_MINES  6
#define WND_Options_ST_NUMBER_OF_MINES  WND_Options + WNDOFFSET_Options_ST_NUMBER_OF_MINES

#define WNDOFFSET_Options_BITMAP_MINE  7
#define WND_Options_BITMAP_MINE  WND_Options + WNDOFFSET_Options_BITMAP_MINE

#define WNDOFFSET_Options_NBTAB_SOUND  8
#define WND_Options_NBTAB_SOUND  WND_Options + WNDOFFSET_Options_NBTAB_SOUND

#define WNDOFFSET_Options_CANVAS_SOUND  9
#define WND_Options_CANVAS_SOUND  WND_Options + WNDOFFSET_Options_CANVAS_SOUND

#define WNDOFFSET_Options_CHK_SOUND  10
#define WND_Options_CHK_SOUND  WND_Options + WNDOFFSET_Options_CHK_SOUND

#define WNDOFFSET_Options_ST_SOUNDTEXT  11
#define WND_Options_ST_SOUNDTEXT  WND_Options + WNDOFFSET_Options_ST_SOUNDTEXT

#define WNDOFFSET_Options_BITMAP_SOUND  12
#define WND_Options_BITMAP_SOUND  WND_Options + WNDOFFSET_Options_BITMAP_SOUND

#define WNDOFFSET_Options_NBTAB_PLAYER  13
#define WND_Options_NBTAB_PLAYER  WND_Options + WNDOFFSET_Options_NBTAB_PLAYER

#define WNDOFFSET_Options_CANVAS_PLAYER  14
#define WND_Options_CANVAS_PLAYER  WND_Options + WNDOFFSET_Options_CANVAS_PLAYER

#define WNDOFFSET_Options_ST_ENTERNAME  15
#define WND_Options_ST_ENTERNAME  WND_Options + WNDOFFSET_Options_ST_ENTERNAME

#define WNDOFFSET_Options_EF_PLAYER_NAME  16
#define WND_Options_EF_PLAYER_NAME  WND_Options + WNDOFFSET_Options_EF_PLAYER_NAME

#define WNDOFFSET_Options_IconControl1  17
#define WND_Options_IconControl1  WND_Options + WNDOFFSET_Options_IconControl1

#define WNDOFFSET_Options_NBTAB_MISC  18
#define WND_Options_NBTAB_MISC  WND_Options + WNDOFFSET_Options_NBTAB_MISC

#define WNDOFFSET_Options_CANVAS_MISC  19
#define WND_Options_CANVAS_MISC  WND_Options + WNDOFFSET_Options_CANVAS_MISC

#define WNDOFFSET_Options_CHK_SMARTOPPONENT  20
#define WND_Options_CHK_SMARTOPPONENT  WND_Options + WNDOFFSET_Options_CHK_SMARTOPPONENT

#define WNDOFFSET_Options_SPIN_NUMBER_OF_TURNS  21
#define WND_Options_SPIN_NUMBER_OF_TURNS  WND_Options + WNDOFFSET_Options_SPIN_NUMBER_OF_TURNS

#define WNDOFFSET_Options_ST_TURNSROUND  22
#define WND_Options_ST_TURNSROUND  WND_Options + WNDOFFSET_Options_ST_TURNSROUND

#define WNDOFFSET_Options_ICON_MISC  23
#define WND_Options_ICON_MISC  WND_Options + WNDOFFSET_Options_ICON_MISC

#define WNDOFFSET_Options_CB_OK  24
#define WND_Options_CB_OK  WND_Options + WNDOFFSET_Options_CB_OK

#define WNDOFFSET_Options_CB_CANCEL  25
#define WND_Options_CB_CANCEL  WND_Options + WNDOFFSET_Options_CB_CANCEL


