/*******************************************************************************
* FILE NAME: Options.hpp                                                       *
*                                                                              *
* DESCRIPTION:                                                                 *
*   Declaration of the class:                                                  *
*     Options                                                                  *
* ---------------------------------------------------------------------------- *
* Warning: This file was generated by the VisualAge C++ Visual Builder.        *
* Modifications to this source file will be lost when the part is regenerated. *
*******************************************************************************/
#ifndef _OPTIONS_
#define _OPTIONS_  

class Options;

#ifndef _IFRAME_
#include <iframe.hpp>
#endif

#ifndef _BatGame_
#include "batshpgm.hpp"
#endif

class ICanvas;
class INotebook;
class IVBNotebookPage;
class ICheckBox;
class INumericSpinButton;
class IStaticText;
class IBitmapControl;
class IEntryField;
class IIconControl;
class IPushButton;
#ifndef _IRECT_
#include <irect.hpp>
#endif

#ifndef _ISTRING_
#include <istring.hpp>
#endif

class OptionsConn0;
class OptionsConn1;
#include "Options.h"


/*----------------------------------------------------------------------------*/
/* Align classes on four byte boundary.                                       */
/*----------------------------------------------------------------------------*/
#pragma pack(4)

//*****************************************************************************
// Class definition for Options
//*****************************************************************************
class Options : public IFrameWindow {
public:
   //---------------------------------------------------------------------------
   // Constructors / destructors
   //---------------------------------------------------------------------------
   Options(
      unsigned long id = WND_Options,
      IWindow* parent = IWindow::desktopWindow(),
      IWindow* owner = 0,
      const IRectangle& rect = defaultFramingSpec(),
      const IFrameWindow::Style& style = defaultStyle(),
      const char* title = defaultTitle());

   virtual  ~Options();

   //---------------------------------------------------------------------------
   // public member functions
   //---------------------------------------------------------------------------
   static const IRectangle defaultFramingSpec();
   static const IFrameWindow::Style defaultStyle();
   static IString defaultTitle();
   virtual Options & initializePart();
   Options * getW_OPTIONS() { return this; };

   //---------------------------------------------------------------------------
   // public member data
   //---------------------------------------------------------------------------
   static const INotificationId readyId;

protected:
   //---------------------------------------------------------------------------
   // protected member functions
   //---------------------------------------------------------------------------
   virtual Boolean makeConnections();
   void saveOptions(void);
   void getOptions(void);

private:
   //---------------------------------------------------------------------------
   // private member data
   //---------------------------------------------------------------------------
   ICanvas * iCanvas;
   INotebook * iNB_OPTIONS;
   IVBNotebookPage * iTB_MINES;
   ICanvas * iCANVAS_MINE;
   ICheckBox * iCK_MINES;
   INumericSpinButton * iSPIN_NUMBER_OF_MINES;
   IStaticText * iST_NUMBER_OF_MINES;
   IBitmapControl * iBITMAP_MINE;
   IVBNotebookPage * iNBTAB_SOUND;
   ICanvas * iCANVAS_SOUND;
   ICheckBox * iCHK_SOUND;
   IStaticText * iST_SOUNDTEXT;
   IBitmapControl * iBITMAP_SOUND;
   IVBNotebookPage * iNBTAB_PLAYER;
   ICanvas * iCANVAS_PLAYER;
   IStaticText * iST_ENTERNAME;
   IEntryField * iEF_PLAYER_NAME;
   IIconControl * iIconControl1;
   IVBNotebookPage * iNBTAB_MISC;
   ICanvas * iCANVAS_MISC;
   ICheckBox * iCHK_SMARTOPPONENT;
   INumericSpinButton * iSPIN_NUMBER_OF_TURNS;
   IStaticText * iST_TURNSROUND;
   IIconControl * iICON_MISC;
   IPushButton * iCB_OK;
   IPushButton * iCB_CANCEL;
   OptionsConn0 * conn0;
   OptionsConn1 * conn1;

   CBattleShipGame* m_pGame;

friend class OptionsConn1;

};   //Options


/*----------------------------------------------------------------------------*/
/* Resume compiler default packing.                                           */
/*----------------------------------------------------------------------------*/
#pragma pack()

#endif
